export const IPAPI_DEFAULT_FIELDS: readonly string[] = [
	'query',
	'status',
	'country',
	'countryCode',
	'continent',
	'continentCode',
	'region',
	'regionName',
	'city',
	'zip',
	'lat',
	'lon',
	'timezone',
	'isp',
	'org',
	'as',
] as const

export enum IPAPIField {
	STATUS = 'status',
	MESSAGE = 'message',
	CONTINENT = 'continent',
	CONTINENT_CODE = 'continentCode',
	COUNTRY = 'country',
	COUNTRY_CODE = 'countryCode',
	REGION = 'region',
	REGION_NAME = 'regionName',
	CITY = 'city',
	DISTRICT = 'district',
	ZIP = 'zip',
	LAT = 'lat',
	LON = 'lon',
	TIMEZONE = 'timezone',
	OFFSET = 'offset',
	CURRENCY = 'currency',
	ISP = 'isp',
	ORG = 'org',
	AS = 'as',
	ASNAME = 'asname',
	REVERSE = 'reverse',
	MOBILE = 'mobile',
	PROXY = 'proxy',
	HOSTING = 'hosting',
	QUERY = 'query',
}
