export enum IPAPIField {
	STATUS = 'status',
	MESSAGE = 'message',
	CONTINENT = 'continent',
	CONTINENT_CODE = 'continentCode',
	COUNTRY = 'country',
	COUNTRY_CODE = 'countryCode',
	REGION = 'region',
	REGION_NAME = 'regionName',
	CITY = 'city',
	DISTRICT = 'district',
	ZIP = 'zip',
	LAT = 'lat',
	LON = 'lon',
	TIMEZONE = 'timezone',
	OFFSET = 'offset',
	CURRENCY = 'currency',
	ISP = 'isp',
	ORG = 'org',
	AS = 'as',
	ASNAME = 'asname',
	REVERSE = 'reverse',
	MOBILE = 'mobile',
	PROXY = 'proxy',
	HOSTING = 'hosting',
	QUERY = 'query',
}

export const IPAPI_DEFAULT_FIELDS: readonly IPAPIField[] = [
	IPAPIField.QUERY,
	IPAPIField.STATUS,
	IPAPIField.COUNTRY,
	IPAPIField.COUNTRY_CODE,
	IPAPIField.CONTINENT,
	IPAPIField.CONTINENT_CODE,
	IPAPIField.REGION,
	IPAPIField.REGION_NAME,
	IPAPIField.CITY,
	IPAPIField.ZIP,
	IPAPIField.LAT,
	IPAPIField.LON,
	IPAPIField.TIMEZONE,
	IPAPIField.ISP,
	IPAPIField.ORG,
	IPAPIField.AS,
] as const
